<?php

return [
        1 => [
        'El Madrid, el mejor club de la historia',
        'Messi vs. Cristiano: la eterna discusión',
        'Los 10 mejores goles de la Champions League',
        'El impacto del VAR en el fútbol moderno',
        'Los secretos del entrenamiento de un atleta olímpico',
        'La evolución del baloncesto en la última década',
        'Fórmula 1: El dominio de Red Bull en la era moderna',
        'El ascenso del pádel como deporte global',
        '¿Quién ganará el Balón de Oro este año?',
        'Los mejores estadios del mundo y su historia',
    ],
        2=> [
        'Tendencias de maquillaje para este año',
        'Los mejores productos para el cuidado de la piel',
        'Cómo mantener un cabello sano y brillante',
        'Errores comunes en la rutina de belleza',
        'Tratamientos faciales que realmente funcionan',
        'Uñas perfectas: trucos y tendencias',
        'El impacto de la alimentación en la piel',
        'Maquillaje natural vs. maquillaje glamuroso',
        'Cuidado de la piel en invierno y verano',
        'Secretos de belleza de las celebridades',
    ],
        3 => [
        '¿Estamos solos en el universo?',
        'El avance de la inteligencia artificial en la ciencia',
        'Cómo funciona la energía nuclear',
        'Los secretos del ADN humano',
        'Las teorías más sorprendentes sobre el tiempo',
        'El cambio climático explicado científicamente',
        'Descubrimientos espaciales recientes',
        'Cómo los experimentos cuánticos desafían la realidad',
        'La importancia de las vacunas en la historia',
        '¿Puede la ciencia prolongar la vida humana?',
    ],
        4 => [
        '10 recetas rápidas y saludables',
        'Cómo hacer la mejor pizza casera',
        'Postres fáciles con pocos ingredientes',
        'El arte de hacer pan en casa',
        'Recetas veganas llenas de sabor',
        'Salsas caseras para cualquier ocasión',
        'Cocina internacional: recetas imprescindibles',
        'Trucos para un asado perfecto',
        'Cómo hacer el mejor café en casa',
        'Los errores más comunes al cocinar pasta',
    ],
        5 => [
        'Cómo mejorar tu calidad de sueño',
        'La importancia de la hidratación en la salud',
        'Ejercicios efectivos para fortalecer el cuerpo',
        'Los beneficios del ayuno intermitente',
        'Meditación: cómo empezar y qué beneficios tiene',
        'El impacto del estrés en la salud',
        'Cómo mejorar la postura y evitar dolores',
        'Alimentos que refuerzan el sistema inmunológico',
        'Los mejores suplementos para una vida sana',
        'Cómo mantener la motivación en el gimnasio',
    ],
        6 => [
        'La IA y el futuro del trabajo',
        'Los smartphones más innovadores del año',
        'Cómo funciona la computación cuántica',
        'Las redes sociales y su impacto en la sociedad',
        'Avances en coches eléctricos y autónomos',
        'Los mejores gadgets para mejorar tu productividad',
        'El impacto del 5G en nuestra vida diaria',
        'Ciberseguridad: cómo proteger tu información',
        '¿Realmente necesitamos el metaverso?',
        'Los mejores lenguajes de programación en la actualidad',
    ],
        7 => [
        'Las mejores series de la última década',
        'Películas de culto que debes ver',
        'Cómo ha cambiado la industria de la música',
        'Los videojuegos más esperados del año',
        'Streaming vs. cine: ¿cuál es el futuro?',
        'Los mejores libros de fantasía y ciencia ficción',
        'Curiosidades sobre Hollywood que no conocías',
        'El auge de los eSports y su impacto global',
        'Las bandas sonoras más icónicas del cine',
        'Cómo los podcasts están revolucionando el entretenimiento',
    ],
        8 => [
        'Los destinos más exóticos para visitar',
        'Cómo viajar barato sin sacrificar comodidad',
        'Los mejores consejos para viajar solo',
        'Ciudades europeas que debes conocer',
        'Las mejores playas del mundo',
        'Consejos para un viaje seguro y sin estrés',
        'Alojamientos únicos alrededor del mundo',
        'Cómo empacar ligero y eficiente',
        'Experiencias gastronómicas que no te puedes perder',
        'El impacto del turismo sostenible en el planeta',
    ],
        9 => [
        'Cómo empezar a invertir sin experiencia',
        'Las criptomonedas y su impacto en la economía',
        'La inflación: causas y efectos',
        'Cómo gestionar tus finanzas personales',
        'El auge de las startups tecnológicas',
        'Consejos para ahorrar más cada mes',
        'El futuro de la banca digital',
        'Impuestos y cómo afectan a tu bolsillo',
        'El impacto de la inteligencia artificial en el mercado laboral',
        'Cómo emprender con éxito en tiempos de crisis',
    ],
        10 => [
        'Las civilizaciones antiguas más fascinantes',
        'Cómo el arte refleja la historia',
        'El impacto de la literatura en la sociedad',
        'Los festivales culturales más importantes del mundo',
        'El papel de la música en la identidad cultural',
        'El cine como herramienta de cambio social',
        'La importancia de preservar las lenguas indígenas',
        'Grandes mitos y leyendas de la historia',
        'Cómo las redes sociales han cambiado la cultura',
        'La evolución del teatro a lo largo del tiempo',
    ],
];
